import React, { useState } from 'react';
import { Lightbulb, ChevronDown, ChevronUp, Sparkles } from 'lucide-react';

/**
 * Displays the 3 personalized tips returned by Gemini during onboarding.
 * Shown on the Dashboard as a welcome card for the first week.
 *
 * Props:
 *   tips: string[]       — the 3 tip strings from Gemini baseline analysis
 *   baselineKg: number   — user's baseline kg/day from onboarding
 */
export default function WelcomeTips({ tips = [], baselineKg }) {
  const [expanded, setExpanded] = useState(true);

  if (!tips || tips.length === 0) return null;

  return (
    <div className="glass-card overflow-hidden animate-slide-up"
         style={{ borderColor: 'rgba(34,197,94,0.2)' }}>
      {/* Header */}
      <button
        onClick={() => setExpanded((e) => !e)}
        className="w-full flex items-center justify-between p-5 text-left hover:bg-white/[0.02] transition-colors"
      >
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-xl bg-green-500/20 flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-green-400" />
          </div>
          <div>
            <p className="text-sm font-semibold text-white flex items-center gap-2">
              Your AI-Personalised Starting Tips
            </p>
            <p className="text-xs text-gray-500 mt-0.5">
              Based on your baseline of <span className="text-green-400 font-medium">{baselineKg ?? '—'} kg CO₂/day</span>
            </p>
          </div>
        </div>
        {expanded
          ? <ChevronUp className="w-4 h-4 text-gray-500 shrink-0" />
          : <ChevronDown className="w-4 h-4 text-gray-500 shrink-0" />}
      </button>

      {/* Tips */}
      {expanded && (
        <div className="px-5 pb-5 space-y-3 border-t border-white/5">
          {tips.map((tip, i) => (
            <div key={i} className="flex items-start gap-3 pt-3">
              <div className="w-6 h-6 rounded-full bg-green-500/20 border border-green-500/30 flex items-center justify-center shrink-0 mt-0.5">
                <span className="text-xs font-bold text-green-400">{i + 1}</span>
              </div>
              <p className="text-sm text-gray-300 leading-relaxed">{tip}</p>
            </div>
          ))}
          <p className="text-xs text-gray-600 pt-1 border-t border-white/5">
            💡 Generated by Gemini AI during your onboarding • personalised to your lifestyle
          </p>
        </div>
      )}
    </div>
  );
}
